export const usersData = [
  {
    name: 'Adewale Johnson',
    email: 'adewale@email.com',
    role: 'Property Manager',
    plan: 'Pro',
    joined: 'Jan 12, 2026',
    status: 'Active',
    properties: 8,
  },
  {
    name: 'Chidinma Okafor',
    email: 'chidinma@email.com',
    role: 'Tenant',
    plan: 'Free',
    joined: 'Jan 18, 2026',
    status: 'Active',
    properties: 0,
  },
  {
    name: 'Emeka Nwosu',
    email: 'emeka@email.com',
    role: 'Landlord',
    plan: 'Basic',
    joined: 'Feb 2, 2026',
    status: 'Active',
    properties: 3,
  },
  {
    name: 'Funmi Adeyemi',
    email: 'funmi@email.com',
    role: 'Tenant',
    plan: 'Free',
    joined: 'Feb 14, 2026',
    status: 'Active',
    properties: 0,
  },
  {
    name: 'Halima Usman',
    email: 'halima@email.com',
    role: 'Service Provider',
    plan: 'Free',
    joined: 'Mar 1, 2026',
    status: 'Active',
    properties: 0,
  },
  {
    name: 'Ibrahim Musa',
    email: 'ibrahim@email.com',
    role: 'Property Manager',
    plan: 'Enterprise',
    joined: 'Mar 5, 2026',
    status: 'Active',
    properties: 24,
  },
  {
    name: 'Kola Adeyemi',
    email: 'kola@email.com',
    role: 'Tenant',
    plan: 'Free',
    joined: 'Mar 20, 2026',
    status: 'Suspended',
    properties: 0,
  },
  {
    name: 'Musa Garba',
    email: 'musa@email.com',
    role: 'Landlord',
    plan: 'Basic',
    joined: 'Apr 3, 2026',
    status: 'Active',
    properties: 5,
  },
  {
    name: 'Ngozi Chukwu',
    email: 'ngozi@email.com',
    role: 'Tenant',
    plan: 'Free',
    joined: 'Apr 10, 2026',
    status: 'Active',
    properties: 0,
  },
  {
    name: 'Sade Akinwale',
    email: 'sade@email.com',
    role: 'Service Provider',
    plan: 'Free',
    joined: 'Apr 22, 2026',
    status: 'Active',
    properties: 0,
  },
  {
    name: 'Tunde Bakare',
    email: 'tunde@email.com',
    role: 'Property Manager',
    plan: 'Pro',
    joined: 'May 1, 2026',
    status: 'Active',
    properties: 12,
  },
  {
    name: 'Yemi Oladipo',
    email: 'yemi@email.com',
    role: 'Tenant',
    plan: 'Free',
    joined: 'May 14, 2026',
    status: 'Inactive',
    properties: 0,
  },
];

export const propertiesData = [
  {
    name: 'Lekki Phase 1 Complex',
    manager: 'Adewale Johnson',
    location: 'Lekki, Lagos',
    type: 'Apartment',
    units: 12,
    listed: 'Jan 15, 2026',
    status: 'Verified',
    views: 4821,
  },
  {
    name: 'Maitama Residences',
    manager: 'Ibrahim Musa',
    location: 'Maitama, Abuja',
    type: 'Detached',
    units: 4,
    listed: 'Feb 2, 2026',
    status: 'Verified',
    views: 2103,
  },
  {
    name: 'Wuse 2 Towers',
    manager: 'Ibrahim Musa',
    location: 'Wuse 2, Abuja',
    type: 'Apartment',
    units: 6,
    listed: 'Feb 10, 2026',
    status: 'Verified',
    views: 1891,
  },
  {
    name: 'Ikeja GRA Flats',
    manager: 'Tunde Bakare',
    location: 'Ikeja, Lagos',
    type: 'Flat',
    units: 8,
    listed: 'Feb 28, 2026',
    status: 'Verified',
    views: 3204,
  },
  {
    name: 'VI Luxury Suites',
    manager: 'Adewale Johnson',
    location: 'Victoria Island, Lagos',
    type: 'Penthouse',
    units: 2,
    listed: 'Mar 5, 2026',
    status: 'Verified',
    views: 7641,
  },
  {
    name: 'Surulere Annex',
    manager: 'Tunde Bakare',
    location: 'Surulere, Lagos',
    type: 'Flat',
    units: 6,
    listed: 'Mar 12, 2026',
    status: 'Pending Review',
    views: 892,
  },
  {
    name: 'Ajah Estate',
    manager: 'Emeka Nwosu',
    location: 'Ajah, Lagos',
    type: 'Terrace',
    units: 4,
    listed: 'Mar 22, 2026',
    status: 'Verified',
    views: 1204,
  },
  {
    name: 'Gwarinpa Courts',
    manager: 'Ibrahim Musa',
    location: 'Gwarinpa, Abuja',
    type: 'Apartment',
    units: 10,
    listed: 'Apr 1, 2026',
    status: 'Verified',
    views: 2847,
  },
  {
    name: 'Banana Island Mansion',
    manager: 'Musa Garba',
    location: 'Banana Island, Lagos',
    type: 'Detached',
    units: 1,
    listed: 'Apr 15, 2026',
    status: 'Pending Review',
    views: 512,
  },
  {
    name: 'Jabi Lake Towers',
    manager: 'Tunde Bakare',
    location: 'Jabi, Abuja',
    type: 'Apartment',
    units: 16,
    listed: 'May 2, 2026',
    status: 'Flagged',
    views: 301,
  },
];

export const transactionsData = [
  {
    ref: 'TXN-78821',
    tenant: 'Adewale Johnson',
    property: 'Lekki Phase 1, Apt 203',
    amount: '₦850,000',
    type: 'Rent',
    method: 'Bank Transfer',
    date: 'Jun 24, 2026',
    status: 'Completed',
  },
  {
    ref: 'TXN-78820',
    tenant: 'Chidinma Okafor',
    property: 'Maitama, Unit 5B',
    amount: '₦1,200,000',
    type: 'Rent',
    method: 'Bank Transfer',
    date: 'Jun 23, 2026',
    status: 'Completed',
  },
  {
    ref: 'TXN-78819',
    tenant: 'Ibrahim Musa',
    property: 'Wuse 2, Apt 14',
    amount: '₦650,000',
    type: 'Rent',
    method: 'Mobile Money',
    date: 'Jun 22, 2026',
    status: 'Pending',
  },
  {
    ref: 'TXN-78818',
    tenant: 'Blessing Eze',
    property: 'Ikeja GRA, Flat 8',
    amount: '₦900,000',
    type: 'Rent',
    method: 'Bank Transfer',
    date: 'Jun 22, 2026',
    status: 'Completed',
  },
  {
    ref: 'TXN-78817',
    tenant: 'Funmi Adeyemi',
    property: 'VI, Apt 12A',
    amount: '₦2,500,000',
    type: 'Rent',
    method: 'Bank Transfer',
    date: 'Jun 21, 2026',
    status: 'Completed',
  },
  {
    ref: 'TXN-78816',
    tenant: 'Kola Adeyemi',
    property: 'Surulere, Unit 3',
    amount: '₦600,000',
    type: 'Rent',
    method: 'Card',
    date: 'Jun 20, 2026',
    status: 'Failed',
  },
  {
    ref: 'TXN-78815',
    tenant: 'Ngozi Chukwu',
    property: 'Gwarinpa, Apt 401',
    amount: '₦750,000',
    type: 'Rent',
    method: 'Card',
    date: 'Jun 19, 2026',
    status: 'Completed',
  },
  {
    ref: 'TXN-78814',
    tenant: 'Emeka Nwosu',
    property: 'Ajah, Flat 1A',
    amount: '₦700,000',
    type: 'Rent',
    method: 'Bank Transfer',
    date: 'Jun 18, 2026',
    status: 'Completed',
  },
  {
    ref: 'TXN-78822',
    tenant: 'Ibrahim Musa',
    property: 'Platform Subscription',
    amount: '₦45,000',
    type: 'Subscription',
    method: 'Card',
    date: 'Jun 17, 2026',
    status: 'Completed',
  },
  {
    ref: 'TXN-78823',
    tenant: 'Adewale Johnson',
    property: 'Platform Subscription',
    amount: '₦25,000',
    type: 'Subscription',
    method: 'Card',
    date: 'Jun 15, 2026',
    status: 'Completed',
  },
];

export const uptimeData = [
  {
    service: 'Web App',
    uptime: '99.98%',
    incidents: 0,
    avgResponse: '87ms',
    status: 'Operational',
    lastChecked: '1 min ago',
  },
  {
    service: 'REST API',
    uptime: '99.91%',
    incidents: 1,
    avgResponse: '124ms',
    status: 'Operational',
    lastChecked: '1 min ago',
  },
  {
    service: 'Auth Service',
    uptime: '100%',
    incidents: 0,
    avgResponse: '43ms',
    status: 'Operational',
    lastChecked: '30s ago',
  },
  {
    service: 'Payment Gateway',
    uptime: '99.72%',
    incidents: 2,
    avgResponse: '210ms',
    status: 'Degraded',
    lastChecked: '1 min ago',
  },
  {
    service: 'SMS/Notifications',
    uptime: '99.85%',
    incidents: 1,
    avgResponse: '380ms',
    status: 'Operational',
    lastChecked: '2 min ago',
  },
  {
    service: 'AI Assistant',
    uptime: '99.60%',
    incidents: 1,
    avgResponse: '1.2s',
    status: 'Operational',
    lastChecked: '1 min ago',
  },
  {
    service: 'File Storage',
    uptime: '100%',
    incidents: 0,
    avgResponse: '52ms',
    status: 'Operational',
    lastChecked: '30s ago',
  },
  {
    service: 'Database (Primary)',
    uptime: '100%',
    incidents: 0,
    avgResponse: '18ms',
    status: 'Operational',
    lastChecked: '30s ago',
  },
  {
    service: 'Database (Replica)',
    uptime: '99.95%',
    incidents: 0,
    avgResponse: '22ms',
    status: 'Operational',
    lastChecked: '30s ago',
  },
  {
    service: 'Email Service',
    uptime: '99.40%',
    incidents: 3,
    avgResponse: '480ms',
    status: 'Operational',
    lastChecked: '1 min ago',
  },
];
