import React from 'react';

export const propertyData = [
  {
    id: 'lekki-phase-1',
    name: 'Lekki Phase 1 Complex',
    location: 'Lekki, Lagos',
    type: 'Apartment',
    units: '12',
    occupancy: '11/12',
    defaultStatus: 'Active' as const,
  },
  {
    id: 'maitama-residences',
    name: 'Maitama Residences',
    location: 'Maitama, Abuja',
    type: 'Detached',
    units: '4',
    occupancy: '4/4',
    defaultStatus: 'Active' as const,
  },
  {
    id: 'wuse-2-towers',
    name: 'Wuse 2 Towers',
    location: 'Wuse 2, Abuja',
    type: 'Apartment',
    units: '6',
    occupancy: '5/6',
    defaultStatus: 'Active' as const,
  },
  {
    id: 'ikeja-gra-flats',
    name: 'Ikeja GRA Flats',
    location: 'Ikeja, Lagos',
    type: 'Flat',
    units: '8',
    occupancy: '7/8',
    defaultStatus: 'Active' as const,
  },
  {
    id: 'vi-luxury-suites',
    name: 'VI Luxury Suites',
    location: 'Victoria Island, Lagos',
    type: 'Penthouse',
    units: '2',
    occupancy: '2/2',
    defaultStatus: 'Active' as const,
  },
  {
    id: 'surulere-annex',
    name: 'Surulere Annex',
    location: 'Surulere, Lagos',
    type: 'Flat',
    units: '6',
    occupancy: '4/6',
    defaultStatus: 'Partial' as const,
  },
  {
    id: 'ajah-estate',
    name: 'Ajah Estate',
    location: 'Ajah, Lagos',
    type: 'Terrace',
    units: '4',
    occupancy: '3/4',
    defaultStatus: 'Partial' as const,
  },
  {
    id: 'gwarinpa-courts',
    name: 'Gwarinpa Courts',
    location: 'Gwarinpa, Abuja',
    type: 'Apartment',
    units: '10',
    occupancy: '10/10',
    defaultStatus: 'Active' as const,
  },
];

export const activeTenants = [
  [
    'Adewale Johnson',
    'Lekki Phase 1',
    'Apt 203',
    'Jan 2025',
    'Dec 2025',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Paid</span>,
  ],
  [
    'Chidinma Okafor',
    'Maitama Residences',
    'Unit 5B',
    'Mar 2025',
    'Feb 2026',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Paid</span>,
  ],
  [
    'Ibrahim Musa',
    'Wuse 2 Towers',
    'Apt 14',
    'Jun 2024',
    'May 2025',
    <span key="status" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Pending</span>,
  ],
  [
    'Blessing Eze',
    'Ikeja GRA Flats',
    'Flat 8',
    'Sep 2024',
    'Aug 2025',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Paid</span>,
  ],
  [
    'Funmi Adeyemi',
    'VI Luxury Suites',
    'Apt 12A',
    'Apr 2025',
    'Mar 2026',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Paid</span>,
  ],
  [
    'Yemi Oladipo',
    'Surulere Annex',
    'Unit 7',
    'Jul 2024',
    'Jun 2025',
    <span key="status" className="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-700">Overdue</span>,
  ],
  [
    'Tunde Bakare',
    'Ajah Estate',
    'Flat 3C',
    'Aug 2024',
    'Jul 2025',
    <span key="status" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Pending</span>,
  ],
  [
    'Ngozi Chukwu',
    'Gwarinpa Courts',
    'Apt 401',
    'Feb 2025',
    'Jan 2026',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Paid</span>,
  ],
  [
    'Emeka Nwosu',
    'Lekki Phase 1',
    'Apt 107',
    'May 2024',
    'Apr 2025',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Paid</span>,
  ],
  [
    'Aisha Bello',
    'Ajah Estate',
    'Flat 1A',
    'Jun 2024',
    'May 2025',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Paid</span>,
  ],
  [
    'Chidi Amaechi',
    'Wuse 2 Towers',
    'Apt 06',
    'Oct 2024',
    'Sep 2025',
    <span key="status" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Pending</span>,
  ],
  [
    'Ola Martins',
    'Gwarinpa Courts',
    'Apt 203',
    'Jan 2025',
    'Dec 2025',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Paid</span>,
  ],
];

export const evictedTenants = [
  [
    'Kola Adeyemi',
    'Surulere Annex',
    'Unit 3',
    'Feb 14, 2026',
    'Non-payment of rent',
    '₦1,800,000',
    <span key="status" className="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-700">Vacated</span>,
  ],
  [
    'Musa Garba',
    'Wuse 2 Towers',
    'Apt 09',
    'Jan 03, 2026',
    'Property damage',
    '₦450,000',
    <span key="status" className="rounded-full bg-orange-100 px-2 py-0.5 text-xs text-orange-700">Legal Action</span>,
  ],
  [
    'Sade Akinwale',
    'Ajah Estate',
    'Flat 2B',
    'Dec 20, 2025',
    'Lease violation',
    '₦0',
    <span key="status" className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">Settled</span>,
  ],
  [
    'Emeka Obi',
    'Ikeja GRA Flats',
    'Flat 5',
    'Nov 11, 2025',
    'Non-payment of rent',
    '₦2,700,000',
    <span key="status" className="rounded-full bg-orange-100 px-2 py-0.5 text-xs text-orange-700">Legal Action</span>,
  ],
  [
    'Halima Usman',
    'Lekki Phase 1',
    'Apt 108',
    'Oct 05, 2025',
    'Subletting without consent',
    '₦0',
    <span key="status" className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">Settled</span>,
  ],
];

export const rentRows = [
  [
    'Adewale Johnson',
    'Lekki Phase 1, Apt 203',
    '₦850,000',
    'Bank Transfer',
    '2 hrs ago',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Issued</span>,
  ],
  [
    'Chidinma Okafor',
    'Maitama, Unit 5B',
    '₦1,200,000',
    'Bank Transfer',
    '5 hrs ago',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Issued</span>,
  ],
  [
    'Ibrahim Musa',
    'Wuse 2, Apt 14',
    '₦650,000',
    'Mobile Money',
    '1 day ago',
    <span key="status" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Pending</span>,
  ],
  [
    'Blessing Eze',
    'Ikeja GRA, Flat 8',
    '₦900,000',
    'Bank Transfer',
    '2 days ago',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Issued</span>,
  ],
  [
    'Funmi Adeyemi',
    'VI, Apt 12A',
    '₦2,500,000',
    'Bank Transfer',
    '3 days ago',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Issued</span>,
  ],
  [
    'Ngozi Chukwu',
    'Gwarinpa, Apt 401',
    '₦750,000',
    'Card',
    '4 days ago',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Issued</span>,
  ],
  [
    'Emeka Nwosu',
    'Lekki Phase 1, Apt 107',
    '₦850,000',
    'Bank Transfer',
    '5 days ago',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Issued</span>,
  ],
  [
    'Aisha Bello',
    'Ajah Estate, Flat 1A',
    '₦700,000',
    'Mobile Money',
    '6 days ago',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Issued</span>,
  ],
];

export const rentTrend = [
  { month: 'Jan', collected: 9400000, expected: 10200000 },
  { month: 'Feb', collected: 10100000, expected: 10200000 },
  { month: 'Mar', collected: 9800000, expected: 10200000 },
  { month: 'Apr', collected: 11200000, expected: 11500000 },
  { month: 'May', collected: 11800000, expected: 12000000 },
  { month: 'Jun', collected: 12400000, expected: 12800000 },
];

export const rentByProperty = [
  { name: 'VI Luxury Suites', amount: 2500000, fill: '#6366f1' },
  { name: 'Maitama Residences', amount: 1200000, fill: '#3b82f6' },
  { name: 'Ikeja GRA Flats', amount: 900000, fill: '#10b981' },
  { name: 'Lekki Phase 1', amount: 850000, fill: '#f59e0b' },
  { name: 'Lekki Ph.1 #107', amount: 850000, fill: '#f97316' },
  { name: 'Gwarinpa Courts', amount: 750000, fill: '#8b5cf6' },
  { name: 'Ajah Estate', amount: 700000, fill: '#ec4899' },
  { name: 'Wuse 2 Towers', amount: 650000, fill: '#14b8a6' },
];

export const paymentMethods = [
  { name: 'Bank Transfer', value: 6, fill: '#3b82f6' },
  { name: 'Mobile Money', value: 2, fill: '#10b981' },
  { name: 'Card', value: 1, fill: '#f59e0b' },
];

export const rentStatus = [
  { name: 'Collected', value: 8550000, fill: '#10b981' },
  { name: 'Pending', value: 650000, fill: '#f59e0b' },
];

export const maintenanceRows = [
  [
    '#MR-041',
    'Lekki Phase 1, Apt 203',
    'AC unit not cooling',
    'Adewale Johnson',
    <span key="priority" className="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-700">High</span>,
    '3',
  ],
  [
    '#MR-042',
    'Wuse 2, Apt 14',
    'Leaking roof',
    'Ibrahim Musa',
    <span key="priority" className="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-700">High</span>,
    '5',
  ],
  [
    '#MR-043',
    'Surulere, Unit 7',
    'Broken door lock',
    'Yemi Oladipo',
    <span key="priority" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Medium</span>,
    '2',
  ],
  [
    '#MR-044',
    'Ajah, Flat 3C',
    'Plumbing issue',
    'Tunde Bakare',
    <span key="priority" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Medium</span>,
    '7',
  ],
  [
    '#MR-045',
    'Ikeja GRA, Flat 8',
    'Electrical fault',
    'Blessing Eze',
    <span key="priority" className="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-700">High</span>,
    '1',
  ],
  [
    '#MR-046',
    'VI, Apt 12A',
    'Paint peeling',
    'Funmi Adeyemi',
    <span key="priority" className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-700">Low</span>,
    '10',
  ],
  [
    '#MR-047',
    'Gwarinpa, Apt 401',
    'Gate motor fault',
    'Ngozi Chukwu',
    <span key="priority" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Medium</span>,
    '4',
  ],
];

export const renewalsRows = [
  [
    'Funmi Adeyemi',
    'VI, Apt 12A',
    'Apt 12A',
    '₦2,500,000/yr',
    'May 15, 2026',
    '15',
    <span key="status" className="rounded-full bg-blue-100 px-2 py-0.5 text-xs text-blue-700">Contacted</span>,
    <button key="action" className="text-xs font-medium text-blue-600 hover:underline">Send Reminder</button>,
  ],
  [
    'Yemi Oladipo',
    'Surulere, Unit 7',
    'Unit 7',
    '₦900,000/yr',
    'May 28, 2026',
    '28',
    <span key="status" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Pending</span>,
    <button key="action" className="text-xs font-medium text-blue-600 hover:underline">Contact Now</button>,
  ],
  [
    'Tunde Bakare',
    'Ajah, Flat 3C',
    'Flat 3C',
    '₦700,000/yr',
    'June 5, 2026',
    '36',
    <span key="status" className="rounded-full bg-yellow-100 px-2 py-0.5 text-xs text-yellow-700">Pending</span>,
    <button key="action" className="text-xs font-medium text-blue-600 hover:underline">Contact Now</button>,
  ],
  [
    'Adewale Johnson',
    'Lekki Phase 1',
    'Apt 203',
    '₦850,000/yr',
    'July 1, 2026',
    '62',
    <span key="status" className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">Not Started</span>,
    <button key="action" className="text-xs font-medium text-blue-600 hover:underline">Contact Now</button>,
  ],
  [
    'Ngozi Chukwu',
    'Gwarinpa Courts',
    'Apt 401',
    '₦750,000/yr',
    'July 15, 2026',
    '76',
    <span key="status" className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Renewed</span>,
    <button key="action" className="cursor-default text-xs font-medium text-gray-400">Done</button>,
  ],
  [
    'Emeka Nwosu',
    'Lekki Phase 1',
    'Apt 107',
    '₦850,000/yr',
    'Aug 1, 2026',
    '93',
    <span key="status" className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">Not Started</span>,
    <button key="action" className="text-xs font-medium text-blue-600 hover:underline">Contact Now</button>,
  ],
  [
    'Chidinma Okafor',
    'Maitama Residences',
    'Unit 5B',
    '₦1,200,000/yr',
    'Aug 20, 2026',
    '112',
    <span key="status" className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">Not Started</span>,
    <button key="action" className="text-xs font-medium text-blue-600 hover:underline">Contact Now</button>,
  ],
  [
    'Blessing Eze',
    'Ikeja GRA Flats',
    'Flat 8',
    '₦900,000/yr',
    'Sep 1, 2026',
    '124',
    <span key="status" className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">Not Started</span>,
    <button key="action" className="text-xs font-medium text-blue-600 hover:underline">Contact Now</button>,
  ],
  [
    'Aisha Bello',
    'Ajah Estate',
    'Flat 1A',
    '₦700,000/yr',
    'Sep 15, 2026',
    '138',
    <span key="status" className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">Not Started</span>,
    <button key="action" className="text-xs font-medium text-blue-600 hover:underline">Contact Now</button>,
  ],
];

