export const mockVendors = [
  {
    id: 1,
    name: 'AquaFix Plumbers',
    category: 'Plumbing',
    rating: 4.8,
    completionRate: 95,
    jobsDone: 142,
    phone: '+234 901 234 5678',
    location: 'Lekki, Lagos',
    available: true,
    responseTime: '< 30 min',
    priceRange: '₦8,000 – ₦40,000',
    avatar: 'bg-blue-500',
    aiMatch: 98,
  },
  {
    id: 2,
    name: 'PowerLine Electricals',
    category: 'Electrical',
    rating: 4.6,
    completionRate: 92,
    jobsDone: 87,
    phone: '+234 802 345 6789',
    location: 'Ikeja, Lagos',
    available: true,
    responseTime: '< 1 hr',
    priceRange: '₦10,000 – ₦60,000',
    avatar: 'bg-yellow-500',
    aiMatch: 61,
  },
  {
    id: 3,
    name: 'FixIt Pro Services',
    category: 'General Repairs',
    rating: 4.5,
    completionRate: 89,
    jobsDone: 203,
    phone: '+234 809 876 5432',
    location: 'VI, Lagos',
    available: false,
    responseTime: '2–4 hrs',
    priceRange: '₦5,000 – ₦25,000',
    avatar: 'bg-green-500',
    aiMatch: 55,
  },
  {
    id: 4,
    name: 'CoolBreeze AC Techs',
    category: 'HVAC / AC Repair',
    rating: 4.9,
    completionRate: 97,
    jobsDone: 64,
    phone: '+234 805 111 2222',
    location: 'Ajah, Lagos',
    available: true,
    responseTime: '< 1 hr',
    priceRange: '₦12,000 – ₦80,000',
    avatar: 'bg-cyan-500',
    aiMatch: 42,
  },
  {
    id: 5,
    name: 'Abuja HomeFix',
    category: 'General Repairs',
    rating: 4.3,
    completionRate: 85,
    jobsDone: 310,
    phone: '+234 803 999 0000',
    location: 'Maitama, Abuja',
    available: true,
    responseTime: '1–2 hrs',
    priceRange: '₦4,000 – ₦20,000',
    avatar: 'bg-purple-500',
    aiMatch: 38,
  },
];

export const mockMaintenanceBoardRequests = {
  new: [
    {
      id: 1,
      title: 'Broken Water Pipe',
      description: 'Main water pipe leaking in kitchen',
      tenant: 'Adewale Johnson',
      property: 'Lekki Phase 1, Apt 203',
      priority: 'high',
      category: 'Plumbing',
      submittedAt: '2 hours ago',
      aiCategory: 'Plumbing - Urgent',
      estimatedCost: '₦15,000 - ₦25,000',
    },
    {
      id: 2,
      title: 'AC Not Cooling',
      description: 'Air conditioner running but not cooling',
      tenant: 'Chidinma Okafor',
      property: 'Maitama, Unit 5B',
      priority: 'medium',
      category: 'HVAC',
      submittedAt: '5 hours ago',
      aiCategory: 'HVAC - Moderate',
      estimatedCost: '₦8,000 - ₦20,000',
    },
  ],
  inProgress: [
    {
      id: 3,
      title: 'Electrical Fault',
      description: 'Power outage in master bedroom',
      tenant: 'Ibrahim Musa',
      property: 'Wuse 2, Apt 14',
      priority: 'high',
      category: 'Electrical',
      submittedAt: '1 day ago',
      assignedTo: 'John Electricals',
      aiCategory: 'Electrical - Urgent',
      estimatedCost: '₦10,000 - ₦18,000',
    },
  ],
  completed: [
    {
      id: 4,
      title: 'Leaking Faucet',
      description: 'Bathroom sink faucet dripping',
      tenant: 'Blessing Eze',
      property: 'Ikeja GRA, Flat 8',
      priority: 'low',
      category: 'Plumbing',
      submittedAt: '3 days ago',
      completedAt: '1 day ago',
      assignedTo: 'AquaFix Plumbers',
      aiCategory: 'Plumbing - Minor',
      actualCost: '₦5,000',
    },
  ],
};

export function getMockMaintenanceDetailRequest(
  requestId: number,
  assignedVendor: any,
  assignedVendorId: any,
) {
  return {
    id: requestId,
    title: 'Broken Water Pipe',
    description:
      'Main water pipe leaking in kitchen. Water is dripping from under the sink and needs urgent attention.',
    category: 'Plumbing',
    priority: 'high' as const,
    status: 'in_progress' as const,
    submittedBy: {
      name: 'Adewale Johnson',
      phone: '+234 803 456 7890',
      email: 'adewale.j@email.com',
    },
    property: 'Lekki Phase 1, Apt 203',
    submittedAt: '2 hours ago',
    updatedAt: '30 minutes ago',
    aiClassification: {
      category: 'Plumbing - Urgent',
      urgency: 'High',
      estimatedCost: '₦15,000 - ₦25,000',
      estimatedTime: '2-4 hours',
      confidence: 94,
    },
    timeline: [
      {
        time: '2 hours ago',
        event: 'Request submitted by tenant',
        status: 'completed',
      },
      {
        time: '1.5 hours ago',
        event: 'AI classified as High Priority Plumbing',
        status: 'completed',
      },
      {
        time: '1 hour ago',
        event: assignedVendor ? `Assigned to ${assignedVendor.name}` : 'Awaiting vendor assignment',
        status: assignedVendorId ? 'completed' : 'pending',
      },
      {
        time: '30 minutes ago',
        event: 'Vendor accepted job',
        status: assignedVendorId ? 'completed' : 'pending',
      },
      {
        time: 'Pending',
        event: 'Vendor en route to property',
        status: 'pending',
      },
      { time: 'Pending', event: 'Work completed', status: 'pending' },
    ],
    images: [
      { id: 1, url: 'Image 1 - Kitchen sink leak' },
      { id: 2, url: 'Image 2 - Water damage under sink' },
    ],
    messages: [
      {
        sender: 'Adewale Johnson',
        time: '2 hours ago',
        message: 'The leak is getting worse, please help urgently!',
      },
      {
        sender: 'Property Manager',
        time: '1 hour ago',
        message: 'We have assigned a plumber. They will contact you shortly.',
      },
      {
        sender: 'AquaFix Plumbers',
        time: '30 minutes ago',
        message: 'On my way. ETA 20 minutes.',
      },
    ],
  };
}
