export const mockPropertyDetails: Record<number, any> = {
  1: {
    id: 1,
    title: '3 Bedroom Luxury Apartment',
    address: 'Block 15, Flat 203, Lekki Phase 1',
    city: 'Lagos',
    state: 'Lagos',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    rentAmount: 850000,
    rentFrequency: 'yearly',
    status: 'Available',
    trustScore: 95,
    verified: true,
    currentTenant: {
      name: 'Adewale Johnson',
      email: 'adewale.j@email.com',
      phone: '+234 803 456 7890',
      moveInDate: 'Apr 15, 2026',
      leaseEnd: 'Apr 14, 2027',
      rentStatus: 'Paid',
      paymentHistory: 'Excellent',
    },
    amenities: ['24/7 Power Supply', 'Borehole', 'Security/CCTV', 'Parking Space', 'Generator'],
    utilities: ['Water Included'],
    description:
      'Beautiful 3-bedroom apartment in the heart of Lekki Phase 1. Features modern finishes, spacious rooms, and excellent security. Close to schools, shopping centers, and major roads.',
    neighborhood: {
      safety: 9,
      accessibility: 8,
      powerReliability: 7,
      waterSupply: 9,
    },
    maintenanceHistory: [
      {
        date: '2 weeks ago',
        issue: 'AC Servicing',
        cost: '₦15,000',
        status: 'Completed',
      },
      {
        date: '1 month ago',
        issue: 'Plumbing Repair',
        cost: '₦8,000',
        status: 'Completed',
      },
      {
        date: '3 months ago',
        issue: 'Painting Touch-up',
        cost: '₦12,000',
        status: 'Completed',
      },
    ],
    financials: {
      yearlyRent: 850000,
      collected: 850000,
      pending: 0,
      maintenanceCosts: 35000,
      netIncome: 815000,
    },
  },
  2: {
    id: 2,
    title: '3 Bedroom Luxury Apartment',
    address: 'Block 15, Flat 203, Lekki Phase 1',
    city: 'Lagos',
    state: 'Lagos',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    rentAmount: 850000,
    rentFrequency: 'yearly',
    status: 'Occupied',
    trustScore: 95,
    verified: true,
    currentTenant: {
      name: 'Adewale Johnson',
      email: 'adewale.j@email.com',
      phone: '+234 803 456 7890',
      moveInDate: 'Apr 15, 2026',
      leaseEnd: 'Apr 14, 2027',
      rentStatus: 'Paid',
      paymentHistory: 'Excellent',
    },
    amenities: ['24/7 Power Supply', 'Borehole', 'Security/CCTV', 'Parking Space', 'Generator'],
    utilities: ['Water Included'],
    description:
      'Beautiful 3-bedroom apartment in the heart of Lekki Phase 1. Features modern finishes, spacious rooms, and excellent security. Close to schools, shopping centers, and major roads.',
    neighborhood: {
      safety: 9,
      accessibility: 8,
      powerReliability: 7,
      waterSupply: 9,
    },
    maintenanceHistory: [
      {
        date: '2 weeks ago',
        issue: 'AC Servicing',
        cost: '₦15,000',
        status: 'Completed',
      },
      {
        date: '1 month ago',
        issue: 'Plumbing Repair',
        cost: '₦8,000',
        status: 'Completed',
      },
      {
        date: '3 months ago',
        issue: 'Painting Touch-up',
        cost: '₦12,000',
        status: 'Completed',
      },
    ],
    financials: {
      yearlyRent: 850000,
      collected: 850000,
      pending: 0,
      maintenanceCosts: 35000,
      netIncome: 815000,
    },
  },
};
